[tool.poetry]
name = "pure-python-website"
version = "0.1.0"
description = ""
authors = ["Anna Tarazanova <an.tarazanova2016@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
